FizzBuzz.Web/Models/FizzBuzzSequence.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="FizzBuzzSequence.cs" company="TCS">
//    Copyright (c) Tata consultancy Services. All rights reserved.
// </copyright>
// <summary>
//   Defines the FizzBuzzSequence type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace FizzBuzz.Web.Models
{
    using System.ComponentModel.DataAnnotations;

    using PagedList;

    /// <summary>
    /// The fizz buzz sequence.
    /// </summary>
    public class FizzBuzzSequence
    {
        /// <summary>
        /// Gets or sets the sequence number.
        /// </summary>
        [Required(ErrorMessage = "Please Enter a Sequence Number")]
        [Range(1, 1000, ErrorMessage = "Value must be between 1 and 1000")]
        [Display(Name = "Enter Sequence Number")]
        public int SequenceNumber { get; set; }

        /// <summary>
        /// Gets or sets the sequence number list.
        /// </summary>
        public IPagedList<string> SequenceNumberList { get; set; }
    }
}

FizzBuzz.Web/Controllers/SequenceController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SequenceController.cs" company="TCS">
//    Copyright (c) Tata consultancy Services. All rights reserved.
// </copyright>
// <summary>
//   Defines the SequenceController type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace FizzBuzz.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Web.Mvc;

    using FizzBuzz.Business;
    using FizzBuzz.Web.Models;
    using FizzBuzz.Web.Utility;

    using PagedList;

    /// <summary>
    /// The sequence controller.
    /// </summary>
    public class SequenceController : Controller
    {
        /// <summary>
        /// The sequence number.
        /// </summary>
        private const string SequenceNumber = "SequenceNumber";

        /// <summary>
        /// Sequence service 
        /// </summary>
        private readonly ISequenceBusiness sequenceBusiness;

        /// <summary>
        /// The maximum page.
        /// </summary>
        private readonly int maximumPage;

        /// <summary>
        /// The minimum page.
        /// </summary>
        private readonly int minimumPage;

        #region Constructor

        /// <summary>
        /// Initializes a new instance of the <see cref="SequenceController" /> class.
        /// </summary>
        /// <param name="sequenceBusiness">a sequence business object</param>
        public SequenceController(ISequenceBusiness sequenceBusiness)
        {
            this.sequenceBusiness = sequenceBusiness;
            this.maximumPage = Convert.ToInt32(ConfigurationManager.AppSettings["MaximumPage"]);
            this.minimumPage = Convert.ToInt32(ConfigurationManager.AppSettings["MinimumPage"]);
        }

        #endregion

        /// <summary>
        /// The index.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult Index()
        {
            var model = this.BuildViewModel(new List<string>(), this.minimumPage);
            return this.View("Index", model);
        }

        /// <summary>
        /// The fizz buzz.
        /// </summary>
        /// <param name="model">
        /// The model.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FizzBuzz(FizzBuzzSequence model)
        {
            if (this.ModelState.IsValid)
            {
                var fizzbuzzList = this.sequenceBusiness.GetSequence(model.SequenceNumber);

                Helper.SetDataToCache(fizzbuzzList, SequenceNumber);

                var viewModel = this.BuildViewModel(fizzbuzzList, this.minimumPage);

                return this.View("Index", viewModel);
            }

            return this.View("Index", model);
        }

        /// <summary>
        /// The get page.
        /// </summary>
        /// <param name="page">
        /// The page.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult GetPage(int page)
        {
            var sequenceList = Helper.GetDataFromCache(SequenceNumber);

            if (sequenceList == null)
            {
                return this.RedirectToAction("Index");
            }

            var model = this.BuildViewModel(sequenceList, page);

            return this.View("Index", model);
        }

        #region private methods

        /// <summary>
        /// The build view model.
        /// </summary>
        /// <param name="fizzbuzzList">
        /// The fizz buzz list.
        /// </param>
        /// <param name="page">
        /// The page.
        /// </param>
        /// <returns>
        /// The <see cref="FizzBuzzSequence"/>.
        /// </returns>
        private FizzBuzzSequence BuildViewModel(IEnumerable<string> fizzbuzzList, int page)
        {
            var model = new FizzBuzzSequence { SequenceNumberList = fizzbuzzList.ToPagedList(page, this.maximumPage) };
            return model;
        }

        #endregion
    }
}

FizzBuzz.Web/Views/Sequence/Index.cshtml
@model FizzBuzz.Web.Models.FizzBuzzSequence
@using (Html.BeginForm("FizzBuzz", "Sequence", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()

    <div class="FizzBuzzsection">
        <div>

            @Html.LabelFor(m => m.SequenceNumber)
            @Html.TextBoxFor(m => m.SequenceNumber, new { Value = "" })

            <input type="submit" name="btnSubmit" value="show" />
        </div>

        @Html.ValidationMessageFor(m => m.SequenceNumber)

        @Html.Partial("_Sequence")
    </div>
    
}

FizzBuzz.Web/Views/Sequence/_Sequence.cshtml
@model FizzBuzz.Web.Models.FizzBuzzSequence
@using PagedList.Mvc
<div>
    @if (Model != null && Model.SequenceNumberList != null && Model.SequenceNumberList.Count > 0)
    {
        foreach (var item in Model.SequenceNumberList)
        {

        <div>
            <span class="@item.Replace(" ","")">
                @Html.DisplayFor(m => item)
            </span>
        </div>

        }

        @Html.PagedListPager(Model.SequenceNumberList, page => Url.Action("GetPage", new { page }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
    }
</div>

FizzBuzz.Web/Views/Shared/_Layout.cshtml
<html>
<head>
    @Styles.Render("~/Content/css")
    <title>FizzBuzz</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
</body>
</html>